{% set name = "mplcursors" %}
{% set version = "0.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/m/mplcursors/mplcursors-{{ version }}.tar.gz
  sha256: d52bc6e6c68371937dcf147d29ddd396f64a610663af006ef9145055bd2dcc84

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools_scm
  run:
    - python >=3.6
    - matplotlib-base >3.1

test:
  imports:
    - mplcursors

about:
  home: https://github.com/anntzer/mplcursors
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: mplcursors provides interactive data selection cursors for Matplotlib. It is inspired from mpldatacursor, with a much simplified API.
  doc_url: https://mplcursors.readthedocs.io/
  dev_url: https://github.com/anntzer/mplcursors

extra:
  recipe-maintainers:
    - hmaarrfk
