{% set name = "mplcursors" %}
{% set version = "0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/m/mplcursors/mplcursors-{{ version }}.tar.gz
  sha256: c3dd848fecf46fbc487408a4060a2e103a5567c10444df0eac8b308c4054e54d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools_scm
  run:
    - python >=3.6
    - matplotlib-base >3.1

test:
  imports:
    - mplcursors

about:
  home: https://github.com/anntzer/mplcursors
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: mplcursors provides interactive data selection cursors for Matplotlib. It is inspired from mpldatacursor, with a much simplified API.
  doc_url: https://mplcursors.readthedocs.io/
  dev_url: https://github.com/anntzer/mplcursors

extra:
  recipe-maintainers:
    - hmaarrfk
