travis:
  secure:
    BINSTAR_TOKEN: E7/9ZsawAJ7TsQageiu0yWRe0IMLtq3+R7AYsRWeFIo6z0Xt8JbB6Igum4olf5xpNGuEDVojsdudYSsRt5BdCih2gMx+UMCDXeZbne9Bovvt6XxXpXvy3ELcGPyuvpBG5eMmpuOBG+I6cxPlZj8DfOxuLmRvN9j0vdHqlrbtDvBlJ6fcqBfwYqENwqwtx8yMNXjax4Oc32kv0cOFejv1AAvHeiPZ2CIvQZdYcGG681HnXP/2UnTLlpR8LJk0h2W44cphKjJdbf6hm9U3tktgrmRgIXarrXKL31hgduSWwHHnZ7ImqTZKd+wmVleRCkm919ViyHOoW+2JdQPEa86Tw4biSgpGkztUAyJ2V0co0A27ABqmyAX/1kamXAQvxVDV/BttGoji2rEX3e0eak+L3q7qDhBBEeneokspUQWIDEx6ay5k5AuepSCeubbnxkRzDZ8R/MynpHi2iQuyIZRGjwBuBsxfL6sb5dYGW8m2pAbS79LkJvtrXRnKj3UkQGN6WJP2jVqNAHPHFp1Nqx1OElv5vCRN1lRa+W67PHBbiGgV53uQmxWoQ4A1NsdtQuO9sxd7N2gAkV5CqYZ3jZB8iQY3X6xR1MrtkinzZ/9JRGsCacteJZmWfMqRmp1BJIeobvktcA5ycJk1SSnxs3khmbgZUGuKiQdQXijEs7GtUpY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
